<a href="https://colab.research.google.com/github/sumana-vemuri/ADATA690-WANG/blob/master/assignments/pandas_aggregate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import string


In [2]:
x=range(5)
type(x)

range

In [3]:
list(x)

[0, 1, 2, 3, 4]

In [4]:
y=np.arange(5)
type(y)

numpy.ndarray

In [5]:
list(y)

[0, 1, 2, 3, 4]

In [6]:
#builder pattern 
a=np.arange(100)
print(a)
#one dimenstion 
a
#2D
b=a.reshape(10,10)
b
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [7]:
string.ascii_uppercase

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [8]:
x=np.arange(100).reshape(10,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [9]:
y=list(string.ascii_uppercase)[0:10]
y

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [10]:
df=pd.DataFrame(x, columns=y)
df

A   B   C   D   E   F   G   H   I   J
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [11]:
df.dtypes
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
A    10 non-null int32
B    10 non-null int32
C    10 non-null int32
D    10 non-null int32
E    10 non-null int32
F    10 non-null int32
G    10 non-null int32
H    10 non-null int32
I    10 non-null int32
J    10 non-null int32
dtypes: int32(10)
memory usage: 480.0 bytes


(10, 10)

In [12]:
#to produce summary statistics
df.describe()

A          B          C          D          E          F  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
std    30.276504  30.276504  30.276504  30.276504  30.276504  30.276504   
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000   
25%    22.500000  23.500000  24.500000  25.500000  26.500000  27.500000   
50%    45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
75%    67.500000  68.500000  69.500000  70.500000  71.500000  72.500000   
max    90.000000  91.000000  92.000000  93.000000  94.000000  95.000000   

               G          H          I          J  
count  10.000000  10.000000  10.000000  10.000000  
mean   51.000000  52.000000  53.000000  54.000000  
std    30.276504  30.276504  30.276504  30.276504  
min     6.000000   7.000000   8.000000   9.000000  
25%    28.500000  29.500000  30.500000  31.500000  
50%    51.000000  52.000000  53.000000  54.000000  
75%    73.500000  74.500000  75.500000  76.500000  
max    96.000000  97.000000  98.000000  99.000000

In [13]:
#the summary statistics does not produce the sum od each column or row
#we use aggregate function 
#default-- aggregate of rows
df.aggregate("sum")

A    450
B    460
C    470
D    480
E    490
F    500
G    510
H    520
I    530
J    540
dtype: int64

In [14]:
df.agg("sum", axis="columns")

0     45
1    145
2    245
3    345
4    445
5    545
6    645
7    745
8    845
9    945
dtype: int64

In [15]:
df.agg(['sum','median','std'])

A           B           C           D           E  \
sum     450.000000  460.000000  470.000000  480.000000  490.000000   
median   45.000000   46.000000   47.000000   48.000000   49.000000   
std      30.276504   30.276504   30.276504   30.276504   30.276504   

                 F           G           H           I           J  
sum     500.000000  510.000000  520.000000  530.000000  540.000000  
median   50.000000   51.000000   52.000000   53.000000   54.000000  
std      30.276504   30.276504   30.276504   30.276504   30.276504

In [16]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[np.nan,np.nan,np.nan]],columns=["A","B","C"])
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [17]:
df.describe()

A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [18]:
df.agg("min", axis="columns")

0    1.0
1    4.0
2    7.0
3    NaN
dtype: float64

In [19]:
x=np.random.randint(0,100,100).reshape(20,5)
x

array([[52, 52,  4, 69, 32],
       [33, 43, 66, 40, 27],
       [89, 93, 27, 32, 62],
       [31, 54, 34, 90,  7],
       [23, 97, 59, 98, 83],
       [74, 54, 59, 23, 81],
       [63, 47, 56, 83, 31],
       [25, 10, 74, 77, 69],
       [93, 84,  5,  1,  5],
       [86,  3, 19, 94,  3],
       [28, 10, 77, 98, 39],
       [54, 41,  4, 50, 63],
       [91, 96, 33, 66, 54],
       [95, 46, 89, 80, 37],
       [ 8,  0, 52, 41, 10],
       [29, 90, 35,  9, 42],
       [50, 65, 55, 47, 28],
       [90, 17, 94, 84, 57],
       [94, 22, 55, 86, 93],
       [74, 67, 54, 97, 41]])

In [20]:
y=string.ascii_uppercase
y

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [21]:
y=list(y)[0:5]
y

['A', 'B', 'C', 'D', 'E']

In [22]:
df = pd.DataFrame(x,columns=y)
df

A   B   C   D   E
0   52  52   4  69  32
1   33  43  66  40  27
2   89  93  27  32  62
3   31  54  34  90   7
4   23  97  59  98  83
5   74  54  59  23  81
6   63  47  56  83  31
7   25  10  74  77  69
8   93  84   5   1   5
9   86   3  19  94   3
10  28  10  77  98  39
11  54  41   4  50  63
12  91  96  33  66  54
13  95  46  89  80  37
14   8   0  52  41  10
15  29  90  35   9  42
16  50  65  55  47  28
17  90  17  94  84  57
18  94  22  55  86  93
19  74  67  54  97  41

In [23]:
df.describe()

A          B          C          D          E
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean   59.100000  49.550000  47.550000  63.250000  43.200000
std    29.277079  31.964577  26.835709  30.739782  26.684512
min     8.000000   0.000000   4.000000   1.000000   3.000000
25%    30.500000  20.750000  31.500000  40.750000  27.750000
50%    58.500000  49.500000  54.500000  73.000000  40.000000
75%    89.250000  71.250000  60.750000  87.000000  62.250000
max    95.000000  97.000000  94.000000  98.000000  93.000000